2025-10-06 15:44:50,004 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:44:50.004553', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BC38DC8050>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 15:49:26,925 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:49:26.925981', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A80D62D0D0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 15:54:46,653 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:54:46.653674', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018AAB303D90>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 15:54:52,422 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:54:52.422526', 'error': None, 'mode': 'real'}
2025-10-06 15:55:03,527 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:55:03.527580', 'error': None, 'mode': 'real'}
2025-10-06 15:55:14,654 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:55:14.654891', 'error': None, 'mode': 'real'}
2025-10-06 15:55:25,773 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:55:25.773749', 'error': None, 'mode': 'real'}
2025-10-06 15:55:36,888 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:55:36.888237', 'error': None, 'mode': 'real'}
2025-10-06 15:55:48,006 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:55:48.006277', 'error': None, 'mode': 'real'}
2025-10-06 15:55:59,119 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:55:59.119791', 'error': None, 'mode': 'real'}
2025-10-06 15:56:10,235 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:56:10.235912', 'error': None, 'mode': 'real'}
2025-10-06 15:56:21,354 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:56:21.354281', 'error': None, 'mode': 'real'}
2025-10-06 15:56:32,487 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:56:32.487895', 'error': None, 'mode': 'real'}
2025-10-06 15:58:38,594 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:58:38.594828', 'error': None, 'mode': 'real'}
2025-10-06 15:58:43,657 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T15:58:43.657103', 'error': None, 'mode': 'real'}
2025-10-06 16:06:10,584 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:06:10.584715', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017163DF69D0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:06:39,001 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:06:39.001863', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000171627BCA50>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:06:41,933 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:06:41.933131', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017163DF5A10>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:06:51,119 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:06:51.118939', 'error': None, 'mode': 'real'}
2025-10-06 16:12:55,552 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': True, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:12:55.552631', 'error': None, 'mode': 'real'}
2025-10-06 16:14:52,468 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:14:52.468851', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DB453FD590>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:15:14,285 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:15:14.285152', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DB4653D350>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:18:17,865 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:18:17.865855', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DB43EA9250>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:18:25,913 - AutomationBot - INFO - Automatización iniciada: {'platform': 'Dashboard', 'action': 'Inicio Manual'}
2025-10-06 16:18:35,865 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:18:35.865045', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DB43E22850>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:19:14,782 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:19:14.782512', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DB46A87E90>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:22:03,227 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:22:03.227192', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DB46B11F10>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:22:33,979 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:22:33.979005', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CA24536390>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:22:34,627 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:22:34.627727', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CA25B992D0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:23:31,682 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:23:31.682553', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F8A493DD90>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:23:32,347 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:23:32.347164', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F8A6295590>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:23:54,580 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:23:54.580869', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F8A3C4C890>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:24:05,129 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:24:05.129925', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F8A67C5810>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
2025-10-06 16:36:27,963 - AutomationBot - INFO - Estado conexión FastAPI: {'is_connected': False, 'base_url': 'http://localhost:8000', 'last_check': '2025-10-06T16:36:27.963258', 'error': "No se pudo conectar al backend: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016A2DCDD490>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))", 'mode': 'demo'}
